language: java
deploy:
  provider: heroku
  api_key:
    secure: n3OOAlf0PfKzIA3UOnUAoIzhbXY988fR9h/VGSSzaLOnBWoqTxkP+b9nfRKrGfEjRt3HOHMDniKVRWUq1xL8a9MASv3/OwwspLHnsF2pRMR2vgPWbVI+lxTAByzEXiiyNQlIYhW+R3XEXD5de8p0xFvVcZE+q/qRxdx7RA8ELcbdXS6demi7JUg1WcSj3m+5OyS6PJe+lBoZJmpyNpTm6Cy+9Q+vLU7O8gqHF1nJTchoyv2mgnLo5xu5Tzq8KFCsj2Pzu4N7UuA5h46XdAA4XXvL3D2c3iafOHrCTCi1Ij5jkaQMmQK2vMdxeslVXx18TierbXEBX1QsiR7Z/HcadGGGfuRYOc3Ai94taX0pyfNOsYRgAsu9OGEi0/20hePdxdyFrZO/TbqWxBpEjRuJI149IIY+vBdjGd26KUvB2fk5j4tSGe79F2KcdOMzQeGb4rlYMyXDTMBzEE83qwGiV4wp7O4E2QKLien9CMmzqrkUx/5NvyWGTHuZdTMtLG69dgOcDOc+DF5RFDStHjNhsLoOeLTpFkhFe/qewWHfgTxPia/sMbpGVhNC7HQz1PzWRqB+wFiA+E/50/r12TwegAP+II6zYXJpUZa35EX3wXOlo9xeVc35o+NBbaMarHjfF/8H501lHE9qkQxL95r16lH4x3sM+RkLkaCqIVGKdws=
  app: indrek-gif-chat
